### ISSUE TITLE
Stuck

### ISSUE THREAD

**Issue by Xizebo** [Brandon702/Wasteland-Driver#6]
When moving backwards while a zombie chases you, at one point when the zombie actually catches up to you he makes it so you can't move backwards anymore

https://cdn.discordapp.com/attachments/700909354957668484/714423782663782431/2020-05-25_12-24-08.mp4

**Comment by Brandon702** [comment]
That is due to hitboxes being odd, will try to adjust, however enemy grabs will be a feature.

**Comment by Brandon702** [comment]
I believe this issue is fixed, or at the very least way less common
